### ISSUE TITLE
Create a possibility to choose which exceptions should be sent to the retry queue and then discarded

### ISSUE THREAD

**Issue by juliofalbo** [Tradeshift/spring-rabbitmq-tuning#14]
Steps:

1: Create an attribute in the @EnableRabbitRetryAndDlq annotation for the Exceptions that will be discarded after the max attempts.

https://github.com/Tradeshift/spring-rabbitmq-tuning/blob/master/src/main/java/com/tradeshift/amqp/annotation/EnableRabbitRetryAndDlq.java#L14
2: Change the logic that is responsible to choose which message should go to Retry queue.

https://github.com/Tradeshift/spring-rabbitmq-tuning/blob/master/src/main/java/com/tradeshift/amqp/annotation/EnableRabbitRetryAndDlqAspect.java#L48
Example:

```java
@RabbitListener(containerFactory = "some-event", queues = "${spring.rabbitmq.custom.some-event.queue}")
@EnableRabbitRetryAndDlq(event = "some-event", onlyRetry = { IllegalArgumentException.class, RuntimeException.class }, 
retryAndDiscart  = { BeanDefinitionValidationException.class, NoSuchBeanDefinitionException.class })
public void onMessage(Message message) {
    ...
}
```

**Comment by andrelugomes** [comment]
How about?

```
@EnableRabbitRetryAndDlq(event = "some-event", 
retryWhen = { IllegalArgumentException.class, RuntimeException.class }, 
discartWhen  = { BeanDefinitionValidationException.class, NoSuchBeanDefinitionException.class },
directToDlqWhen  = { CriticalException.class })
```

Something like that.

**Comment by juliofalbo** [comment]
@andrelugomes , IMO it is really nice!

**Comment by wesleyegberto** [comment]
Also, it would be nice if we had an option to define if the exception verification should use the `instanceof` operator to allow it to capture children.
So if we use `checkInheritance = true, retryWhen = { IllegalArgumentException.class }` than it should capture NumberFormatException.

**Comment by wesleyegberto** [comment]
I've started an implementation for this feature and also included some testing.

https://github.com/wesleyegberto/spring-rabbitmq-tuning/tree/issue-14

**Comment by juliofalbo** [comment]
@wesleyegberto really nice suggestion!!

Thank you very much for your help!

**Comment by wesleyegberto** [comment]
Just commenting some thoughts about this:

**1) Checking priority that should be used**
In my commit I used the priority bellow, as you can check [here](https://github.com/wesleyegberto/spring-rabbitmq-tuning/blob/issue-14/src/main/java/com/tradeshift/amqp/annotation/EnableRabbitRetryAndDlqAspect.java#L48).
- Should be discarted
- Should be sent to retry
- Should be sent to DLQ
- Otherwise discart


**2) Backwards compatibility**
In the commit I kept the compatibility by doing [this](https://github.com/wesleyegberto/spring-rabbitmq-tuning/blob/c6d14f52dacd25c22ba246cda9e3d8695bb75522/src/main/java/com/tradeshift/amqp/annotation/EnableRabbitRetryAndDlqAspect.java#L113), allowing this code `@EnableRabbitRetryAndDlq(event = "some-event")` to work without modifications.

By doing so, and if the lib uses the checking priority defined in 1, it won't allow this code to work `@EnableRabbitRetryAndDlq(event = "some-event", directToDlqWhen = NumberFormatException.class)` (case where we would ignore only one exception and retry any other) because the code `exceptions.contains(Exception.class)` would be true before the DLQ list checking.

[Here](https://github.com/wesleyegberto/spring-rabbitmq-tuning/blob/7bd1ec3e14b8f3b48bfb316c3d28357ea4e36911/src/test/java/com/tradeshift/amqp/annotation/EnableRabbitRetryAndDlqAspectTest.java#L209) is a test case to demonstrate.

The priority bellow solves the problem:
- Should be discarted
- Should be sent to DLQ
- Should be sent to retry
- Otherwise discart

IMO the DLQ list should be verified before as I think we would define the exceptions of our retry list.

**Comment by juliofalbo** [comment]
@wesleyegberto I think the you are already implemented this feature. Can you open the PR please?

**Comment by juliofalbo** [comment]
> By doing so, and if the lib uses the checking priority defined in 1, it won't allow this code to work @EnableRabbitRetryAndDlq(event = "some-event", directToDlqWhen = NumberFormatException.class) (case where we would ignore only one exception and retry any other) because the code exceptions.contains(Exception.class) would be true before the DLQ list checking.

About this, we should verify only if we have the argument.

Example:
`@EnableRabbitRetryAndDlq(event = "some-event")` -> Will retry the children of `Exception.class`

`@EnableRabbitRetryAndDlq(event = "some-event", directToDlqWhen = NumberFormatException.class)` -> Will verify if `exceptions` is null, if it is, we need to check only `discardWhen`

**Comment by juliofalbo** [comment]
@wesleyegberto, based on your code, I finalized the task!

Thank you very much!
